### ISSUE TITLE
[request] add markdown or BBCode (or both) to the "Contributions" field

### ISSUE THREAD

**Issue by D4n2021** [WikipediaLibrary/TWLight#1336]
on the user page (example https://wikipedialibrary.wmflabs.org/users/12345/ ), please add ability to use a lightweight markup language in the "Contributions" field. Links in there currently are not clickable.

**Comment by suecarmol** [comment]
Thank you for making this request. We don't track issues here but in https://phabricator.wikimedia.org/tag/library-card-platform/. Please create a ticket there and we will triage it.
