### ISSUE TITLE
cleanup include_invalid model manager

### ISSUE THREAD

**Issue by jsnshrmn** [WikipediaLibrary/TWLight#203]
note to self

**Comment by Samwalton9** [comment]
`include_invalid` is overwriting any previous or inherent filtering of querysets and returning _all_ objects. Had to filter editor specifically in https://github.com/WikipediaLibrary/TWLight/commit/ad4e5a6de14d00c14cbdfd40ef90df6ab015eda2, but we should avoid that issue coming up in the first place.

**Comment by Samwalton9** [comment]
Closing this in favour of https://phabricator.wikimedia.org/T236678
