### ISSUE TITLE
docker-compose up command

### ISSUE THREAD

**Issue by Vinit-Dantkale** [WikipediaLibrary/TWLight#372]
```
Status:_ Downloaded newer image for nginx:latest
Creating twlight_db_1 ... error                                                                                         
ERROR: for twlight_db_1  Cannot create container for service db: invalid volume specification: 'C:\Users\Vinit\Desktop\WIkiLibrary\TWLight\secrets\DJANGO_DB_NAME:/run/secrets/DJANGO_DB_NAME:ro'

ERROR: for db  Cannot create container for service db: invalid volume specification: 'C:\Users\Vinit\Desktop\WIkiLibrary\TWLight\secrets\DJANGO_DB_NAME:/run/secrets/DJANGO_DB_NAME:ro'
ERROR: Encountered errors while bringing up the project.

C:\Users\Vinit\Desktop\WIkiLibrary\TWLight>docker-compose exec twlight /app/bin/virtualenv_migrate.sh
ERROR: No container found for twlight_1`
```
I googled this issue though got only 3 results. Whats the problem here?  (Using on Windows OS)

**Comment by jsnshrmn** [comment]
Hmm. I'm also on windows, and I'm not having this issue.

I'm assuming you're literally running `docker-compose up`? (which is what I would expect)

The first place I'd look would be shared drives under docker settings to verify that your `C:` drive is accessible to be mounted by the containers.

I also have `tcp://localhost:2375` exposed (under general settings) to enable WSL tools to talk to the docker daemon, but I don't see how that would come into play here.

If none of is helpful, maybe you could let me know your windows version? you can get this by hitting the start/windows button, typing `winver` and hitting enter. You docker version (all the info from "about docker desktop") would be helpful too.

**Comment by jsnshrmn** [comment]
My working setup is:
Windows 10 Pro
```
Windows Version 1909 (OS Build 18363.476)
```
Docker Desktop:
![DockerDesktop-2019-12-10 150340](https://user-images.githubusercontent.com/2986893/70568875-6266c700-1b5e-11ea-94e5-366c96bbc40b.png)

**Comment by Vinit-Dantkale** [comment]
`winver`

![image](https://user-images.githubusercontent.com/32016324/70811598-eaadcc00-1deb-11ea-8c7c-6b431e594d9f.png)

I ran `docker-compose build && docker-compose up`
I went on to install Docker desktop and realized that Windows 10 Pro requirement is not fulfilled.I think I will try on Ubuntu 18.04 .
![image](https://user-images.githubusercontent.com/32016324/70811549-cb16a380-1deb-11ea-8f1b-ae2f1512bc13.png)

If I can still continue with this, that will be great. Thank You so much for looking in 😄 .
