### ISSUE TITLE
Database in not connecting

### ISSUE THREAD

**Issue by sanyam-git** [WikipediaLibrary/TWLight#398]
I tried to install the repository using the instructions given in readme file. But on running the container database is refusing to connect.

The steps I followed from the start (I am including the smallest steps ,so as not to miss anything)- 

**Installing docker and docker-compose**
1. installed docker from https://docs.docker.com/install/linux/docker-ce/ubuntu/
2. added settings to manage docker as non-root user https://docs.docker.com/install/linux/linux-postinstall/
3. installed docker-compose from https://docs.docker.com/compose/install/

**Installing TWLight**
1. git clone the repository
2. get in the repository directory and run `docker-compose build && docker-compose up`
3. it runs smoothly but throws an error at the last when trying to connect to the database, continuosly displays the message.**error message** :
`db_1       | 2020-01-31 12:28:12 16 [Warning] Aborted connection 16 to db: 'unconnected' user: 'unauthenticated' host: 'twlight_twlight_1.twlight_default' (This connection closed normally without authentication)`

![error-1](https://user-images.githubusercontent.com/43791665/73450187-e5e8ab80-438a-11ea-8c95-49ce8bd2a2d9.png)
![error-2](https://user-images.githubusercontent.com/43791665/73450188-e5e8ab80-438a-11ea-9953-f4a24ee26453.png)
<br><br>

4. when trying to run migrations through the command `docker-compose exec twlight /app/bin/virtualenv_migrate.sh`. It shows Waiting for DB
![migrations](https://user-images.githubusercontent.com/43791665/73450190-e6814200-438a-11ea-948f-f710a45ea61b.png)
<br><br>

5. Visiting to [localhost](http://localhost/) gives the following error page  <br>
**error message** :
`OperationalError at /
(1130, "Host 'twlight_twlight_1.twlight_default' is not allowed to connect to this MariaDB server")`
![web_error](https://user-images.githubusercontent.com/43791665/73450192-e6814200-438a-11ea-823c-05cc72df18ef.png)
<br><br>
and on visiting  [127.0.0.1](http://127.0.0.1/) displays :
![127](https://user-images.githubusercontent.com/43791665/73451075-c8b4dc80-438c-11ea-9f5e-cd3b5e8dde72.png)

**System Specs :**
- OS : Linux Mint 19.3 Cinnamon (tried it on Ubuntu 18.04.3 also)
- Docker version : 19.03.5, build 633a0ea838
- Docker-compose version : version 1.25.3, build d4d1b42b
- repository status : last [commit](https://github.com/WikipediaLibrary/TWLight/commit/4c9f52ed92a398acf71747b0494757263cd2424a)

**Already Tried Solutions**
- reinstalling docker, docker-compose and the repo.
- checked : no other app/database server/service is running on 127.0.0.1 or localhost.

I have [hashtags](https://github.com/WikipediaLibrary/hashtags) working completely fine on the same system with no issues with database or any other. (functioning with docker and docker-compose).
I tried to include most minute details in the issue. Thanks in Advance ! :+1:

**Comment by jsnshrmn** [comment]
@sanyam-git It looks like you're doing all the right things here, so I'll spin up a ubuntu 18.04 vm and see if I can reproduce.

**Comment by sanyam-git** [comment]
@jsnshrmn were you able to reproduce the issue, any update ?

**Comment by jsnshrmn** [comment]
@sanyam-git not so far. I've tried a few different iterations of a fresh ubuntu 18.04.3 vm, and so far it works every time.

**Comment by jsnshrmn** [comment]
based on the errors your seeing, it looks like the db is up, but that django isn't correctly picking up the credentials. That stuff is all there in the git checkout, so I'm wondering if you have git tree on an interesting filesystem, like something remotely mounted, or ntfs, something like that?

**Comment by sanyam-git** [comment]
- performed `git checkout` I am getting this `Your branch is up to date with 'origin/master'.`

- I forget to mention earlier that I use a dual boot system with Windows 10 (use NTFS file system) and Mint 19.3.

- I checked the disk partitions and it showed that Linux Mint is not using NTFS 
and the windows partitions are unmounted.

![Screenshot from 2020-02-02 00-26-10](https://user-images.githubusercontent.com/43791665/73566589-3eeb3900-448a-11ea-915f-c0bd36ad0f78.png)

Hope this can help.

**Comment by sanyam-git** [comment]
Till this issue isn't fixed, is there any alternate way to setup TWLight on my machine? 
Does using  VM  feasible to run the app and can you provide some info about what VM to use and other 
 required details. Thanks!

**Comment by jsnshrmn** [comment]
When I spoke about setting up a VM, I was referring to one that then gets docker setup on it. You would just go through the exact same steps you've already done within the VM.

**Comment by jsnshrmn** [comment]
It's been a little while since I've heard back from you. @sanyam-git were you able to try the setup from within a VM? Success? Failure?

**Comment by sanyam-git** [comment]
Thanks @jsnshrmn for helping with issue. But no succees so far, even with the VM I am getting the same issue.

**Comment by jsnshrmn** [comment]
can you post the output of printenv from the twlight container? e.g. something like `docker-compose exec twlight printenv`?

**Comment by sanyam-git** [comment]
The output of pritenv from the twlight container:
```
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/pandoc-2.7.1/bin
HOSTNAME=172996a674c9
TERM=xterm
DJANGO_DB_HOST=db
DJANGO_EMAIL_BACKEND=django.core.mail.backends.console.EmailBackend
DJANGO_EMAIL_ADMINS_BACKEND=django.core.mail.backends.dummy.EmailBackend
DJANGO_EMAIL_HOST=localhost
DJANGO_SETTINGS_MODULE=TWLight.settings.local
TWLIGHT_HOME=/app
TWLIGHT_DUMP_DIR=
TWLIGHT_MYSQLDUMP_DIR=/app/TWLight
TWLIGHT_BACKUP_DIR=/app/backup
TWLIGHT_ENV=local
TWLIGHT_UNIXNAME=root
TWLIGHT_ERROR_MAILTO=wikipedialibrary@wikimedia.org
USER=root
ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
REQUEST_BASE_URL=http://localhost/
DEBUG=True
TWLIGHT_OAUTH_PROVIDER_URL=https://meta.wikimedia.org/w/index.php
TWLIGHT_EZPROXY_URL=https://wikipedialibrary.idm.oclc.org:9443
GUNICORN_CMD_ARGS=--name twlight --workers 1 --backlog 2048 --timeout 300 --bind=-0.0.0.0:80 --forwarded-allow-ips * --reload --log-level=info
PYTHONUNBUFFERED=1
PYTHONPATH=/app:/usr/lib/python3.7
HOME=/root

```

**Comment by QEDK** [comment]
https://stackoverflow.com/questions/1559955/host-xxx-xx-xxx-xxx-is-not-allowed-to-connect-to-this-mysql-server/1559992 might be relevant.
Can you try running it on root (rootless is an experimental feature afaik)?

**Comment by jsnshrmn** [comment]
@sanyam-git your container doesn't seem to have loaded the "secrets" for the development environment. Here's a fresh `printenv` from my dev environment. Notice that there is a db password in there, among other things?
```
TWLIGHT_EZPROXY_SECRET=twlight
TWLIGHT_API_PROVIDER_ENDPOINT=https://meta.wikimedia.org/w/api.php
TWLIGHT_OAUTH_CONSUMER_SECRET=3c89911e1981b9bc2777618eeca4e7d22d25821e
PWD=/app
TWLIGHT_UNIXNAME=root
DJANGO_DB_HOST=db
GUNICORN_CMD_ARGS=--name twlight --workers 1 --backlog 2048 --timeout 300 --bind=-0.0.0.0:80 --forwarded-allow-ips * --reload --log-level=info
DJANGO_DB_PASSWORD=twlight
HOME=/root
VIRTUAL_ENV=/venv
SECRET_KEY=twlight
TWLIGHT_DUMP_DIR=
TWLIGHT_BACKUP_DIR=/app/backup
DJANGO_SETTINGS_MODULE=TWLight.settings.local
DJANGO_DB_NAME=twlight
DJANGO_EMAIL_BACKEND=django.core.mail.backends.console.EmailBackend
PYTHONPATH=/app:/venv:/usr/lib/python3.8
TERM=xterm
USER=root
TWLIGHT_EZPROXY_URL=https://wikipedialibrary.idm.oclc.org:9443
SHLVL=1
DJANGO_DB_USER=twlight
TWLIGHT_MYSQLDUMP_DIR=/app/TWLight
REQUEST_BASE_URL=http://localhost/
PS1=(venv) ${debian_chroot:+($debian_chroot)}\w\$ 
DJANGO_EMAIL_ADMINS_BACKEND=django.core.mail.backends.dummy.EmailBackend
GCC_COLORS=error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01
TWLIGHT_OAUTH_CONSUMER_KEY=42b486d69d24a109c49e12673895b3aa
PATH=/venv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/pandoc-2.7.1/bin
DEBUG=True
TWLIGHT_ERROR_MAILTO=wikipedialibrary@wikimedia.org
TWLIGHT_OAUTH_PROVIDER_URL=https://meta.wikimedia.org/w/index.php
OLDPWD=/app
```

those should be getting pulled from the files under the `./secrets` directory in the project.

**Comment by sanyam-git** [comment]
@QEDK tried with `root` also, no change same issue persists.

**Comment by sanyam-git** [comment]
@jsnshrmn , Yep this should be the reason why it is not allowed to connect to the db.

**Comment by jsnshrmn** [comment]
@sanyam-git yes, they are just used to set environment variables in the guest vm. See `bin/twlight_docker_secrets.sh` which is supposed to do that for you.

**Comment by jsnshrmn** [comment]
But I'm pretty baffled as to why this wouldn't be working for you in the first place. Do the files in your `secrets` directory on the host match up with what's visible in  the codebase on github? Do those files seem to be mounted under `/run/secrets` in your twlight container?

**Comment by sanyam-git** [comment]
@jsnshrmn 
- tried manually running `./twlight_docker_secrets.sh`, no change
- check secrets files at local with that on github repo, no difference
 
I did't found any folder/ file with name as `secrets` under `/run/` directory. Is there need to be one ?

**Comment by jsnshrmn** [comment]
you are correct if you don't have `/run/secrets` then you don't have the data source for those environment variables inside the container. I'm not sure why that would be the case, unless the override file isn't being applied for some reason. You can check by running `docker-compose -f docker-compose.yml -f docker-compose.override.yml` and see if that fixes your issue. It shouldn't make a difference, but then again this issue has been pretty baffling to me.

**Comment by sanyam-git** [comment]
As mentioned by you `docker-compose -f docker-compose.yml -f docker-compose.override.yml` didn't made any difference, Can you give me the contents of `/run/secrets`, I can manually place them at the required destination and give it a try. Thanks for helping me so far with the issue :)

**Comment by jsnshrmn** [comment]
It's literally just the contents of the `secrets` directory in the project

**Comment by jsnshrmn** [comment]
Closing out due to lack of activity.
