### ISSUE TITLE
the Brazilian Portuguese language is not configured correctly

### ISSUE THREAD

**Issue by eduaddad** [WikipediaLibrary/TWLight#467]
When selecting the Brazilian Portuguese language, Portuguese Portuques is used.

**Comment by eduaddad** [comment]
https://github.com/WikipediaLibrary/TWLight/blob/master/locale/pt-br/LC_MESSAGES/django.po is getting some translations from European Portuguese

for example : https://translatewiki.net/wiki/Wikimedia:Wikipedia-library-84c290-Username/pt-br and https://translatewiki.net/wiki/Wikimedia:Wikipedia-library-89b86a-Language/pt-br

**Comment by uyscuti-wiki** [comment]
Hi, thank you for reporting this. All translations are performed by volunteer translators from [translatewiki.net](https://translatewiki.net/). Could you please create an account yourself and edit the translation yourself, or request the language be changed on the [support page](https://translatewiki.net/wiki/Support)?

**Comment by eduaddad** [comment]
the translations of translatewiki.net are right but the site is getting pt-pt

**Comment by eduaddad** [comment]
![](https://phab.wmfusercontent.org/file/data/t45fn26o27v2pdeq7qmg/PHID-FILE-njeezoid335fjeguocnp/ph_1.png)

https://translatewiki.net/wiki/Wikimedia:Wikipedia-library-1a9863-Browse_Partners/pt-br

**Comment by uyscuti-wiki** [comment]
Ah, got it.

**Comment by Samwalton9** [comment]
Thanks for clarifying - we don't track issues on Github so let's consolidate conversation at https://phabricator.wikimedia.org/T255956.
