### ISSUE TITLE
Test class added in another class in application/tests

### ISSUE THREAD

**Issue by lalit97** [WikipediaLibrary/TWLight#496]
I think `ListApplicationsTest` is added into `EvaluateApplicationTest` by mistake. Refer [applications/tests.py#L3504](https://github.com/WikipediaLibrary/TWLight/blob/master/TWLight/applications/tests.py#L3504).

I could not found anything helpful related to process of raising issues in the [docs](https://github.com/WikipediaLibrary/TWLight/wiki). Should I create a task for it on Phabricator?

Also can I raise a PR for this issue?

**Comment by Samwalton9** [comment]
This is a great point - looks like it was added by @jsnshrmn?

**Comment by jsnshrmn** [comment]
I agree, since `ListApplicationsTest` doesn't do anything there, and is defined elsewhere where tests are actually run. This looks like a merge error to me. We rewrote many commits many times for rebases while working on the bundle code.

**Comment by lalit97** [comment]
> I agree, since `ListApplicationsTest` doesn't do anything there, and is defined elsewhere where tests are actually run. This looks like a merge error to me. We rewrote many commits many times for rebases while working on the bundle code.

Oh likely to happen when you people are working on big features like bundle :D


> I could not found anything helpful related to process of raising issues in the [docs](https://github.com/WikipediaLibrary/TWLight/wiki). Should I create a task for it on Phabricator? Also can I raise a PR for this issue?

Need your view on these points also.

**Comment by Samwalton9** [comment]
> Need your view on these points also.

Just filing a PR would be sufficient, if you're happy to work on it!

**Comment by lalit97** [comment]
> Just filing a PR would be sufficient, if you're happy to work on it!

filed one, thank you :)

**Comment by jsnshrmn** [comment]
Closed by #498
