### ISSUE TITLE
New to this Project

### ISSUE THREAD

**Issue by Rahul-3000** [WikipediaLibrary/TWLight#499]
Hey mates!!
I m Rahul Pawar. I m new to this project and interested in contributing to this project. I know python, CPP, c and, web development.
Please, anyone, guide me on how I can contribute. I can also help in documentation work.

**Comment by jsnshrmn** [comment]
You might check out our getting started page
https://github.com/WikipediaLibrary/TWLight/wiki/Getting-Started

as well as our good 1st tasks list:
https://meet.google.com/linkredirect?authuser=0&dest=https%3A%2F%2Fphabricator.wikimedia.org%2Fproject%2Fboard%2F2765%2Fquery%2FrCNFr9ipmEnt%2F

**Comment by jsnshrmn** [comment]
Closing this issue out.
