### ISSUE TITLE
New member!

### ISSUE THREAD

**Issue by Rahul-3000** [WikipediaLibrary/TWLight#517]
Hey folks!
I'm Rahul Pawar a B.tech second-year student at Visvesvarya National Institute of Technology, Nagpur, India. I am a newbie but have tried frontend mentor challenge, 2-star coder in Codechef, Gold medal in C, Cpp, Python in hackerRank. I'm interested in working with this organization and even participate in GSOC 2021. SO any mentor out there to guide me.
Thanks in advance.
Regards
Rahul Pawar

**Comment by Samwalton9** [comment]
Hi Rahul, I just responded to your email so I'm going to close this :)
