### ISSUE TITLE
with environment setup

### ISSUE THREAD

**Issue by Rahul-3000** [WikipediaLibrary/TWLight#524]
Can anyone please help me with the environment setup. I have got docker and docker-compose. I ran a command docker-compose build && docker-compose up but its no getting complete I have attached the Screenshots please help me.
![Screenshot from 2020-09-13 10-42-37](https://user-images.githubusercontent.com/52457974/93010880-a172ee80-f5ae-11ea-98c6-360ad5daa0d4.png)
![Screenshot from 2020-09-13 10-44-10](https://user-images.githubusercontent.com/52457974/93010881-a59f0c00-f5ae-11ea-9583-b2fc5c481559.png)

**Comment by jsnshrmn** [comment]
This looks like it was working? The `docker-compose up` command doesn't detach unless you tell it to. I'd expect the platform to be accessible at `http://localhost` if you leave docker-compose running.

**Comment by Rahul-3000** [comment]
I kept it running for some 4 to 5 hrs
Should I try it for one more time

**Comment by jsnshrmn** [comment]
so you're not able to access `http://localhost` from this ubuntu host while this is up?

**Comment by Rahul-3000** [comment]
Yes, it sticks to the screen shot screen for hours

**Comment by jsnshrmn** [comment]
Yes, I'd expect that terminal window to stay open indefinitely. What happens when you open firefox and go to http://localhost ?

**Comment by Rahul-3000** [comment]
Jason actually my command of docker-compose build && docker-compose up
never reached completion it got stuck to some web thing (refer the
screenshot in the issue) and when I tried to access the localhost using
Django command (python3 manage.py runserver) it gave an error related to
secrete key. it can't be empty. Please check the attachment. I think I have
messed the whole process.

**Comment by jsnshrmn** [comment]
@Rahul-3000 
That command isn't stuck, the process is attached to your shell. It's listening waiting for you to access the webserver. You don't need to run any more commands, you can literally just open firefox and browse to http://localhost while that shell is open.

**Comment by Rahul-3000** [comment]
Yup thank for help
When I open localhost it's showing Wikipedia library card platform.

**Comment by jsnshrmn** [comment]
I'm glad you were able to get going! Closing out this issue.
